### PR TITLE
Implement new Hooks feature

### LINKED ISSUE #87: Suggestion for new hook feature: When certificate request is succeeded execute hook
Maybe in some cases, one can make use of the hook options on [acme.sh](https://github.com/acmesh-official/acme.sh) client, but when some restricted actions must be executed on a controlled zone, like creation of an object in LDAP or AD by specific service accounts, it would be nice to consider the possibility to execute a hooks once the certificate request has been succeeded.

On our case when creating a Certificate request using AD CA, is required to ensure that the object exists in Active Directory due specific authorisation mechanisms, could it be a feasible option to have this hook, accepting some parameters like the fqdn?

We would be happy to create a PR for this new feature

### PR DESCRIPTION
**Pull request by mlegner**
Add a `Hooks` class, which provides three different methods:
- pre_hook (run before obtaining any certificates)
- post_hook (run after *attempting* to obtain/renew certificates; runs regardless of whether
  obtain/renew succeeded or failed)
- success_hook (run after each successfully renewed certificate)

Each method should throw an Exception if an unrecoverable error occurs.

This class contains dummy implementations of these hooks. To actually use hooks, one should create a
subclass and overwrite one or multiple of the methods. The class file can be configured through the `Hooks`
section with parameter `hooks_file` in the config file.

I'm not 100% sure about the intended behavior if one of the hooks fails, please let me know what you think about that, @grindsa.

Closes #87 

/cc @grindsa @flphrrr

### CODE REVIEW

**Comment by mlegner** [comment]
@grindsa Thanks for taking over this new feature. Do you agree with the general approach and setup?

Is there anything else I can contribute?

**Comment by grindsa** [comment]
Good job. I like your approach and created a [ separate branch](https://github.com/grindsa/acme2certifier/tree/hooks). Give me few days to play with it...

**Comment by grindsa** [comment]
I did some smaller changes but overall it looks pretty good.
- I think we should not load the stub Hooks class by default so I changed the behaviour in 3431ccfc and fb510ef22
- I added some unittests (e707a37ab), a Github action for regression testing (36f717370) and some [documentation](https://github.com/grindsa/acme2certifier/blob/hooks/docs/hooks.md)

I plan to release v.21 later this week which will include the hook feature. So thank you very much for your contribution.

**Comment by flphrrr** [comment]
just testing, but looks that I´m missing something as I´m getting following error when loading new changes:

```syslog
Traceback (most recent call last):
 File "./acme2certifier_wsgi.py", line 13, in <module>
 from acme_srv.certificate import Certificate
 File "./acme_srv/certificate.py", line 10, in <module>
 from acme_srv.threadwithreturnvalue import ThreadWithReturnValue
 ModuleNotFoundError: No module named 'acme_srv.threadwithreturnvalue'
```

Any idea?

**Comment by flphrrr** [comment]
Just found that it was introduced few months ago and I was testing an older version without it 😅

**Comment by flphrrr** [comment]
something as well to mention,  I´m creating an specific hook that creates the object in Active Directory and I would like to share my experience to understand if there is something avoidable here:

- If the hooks experience a exception I cause an error on overall Certificate Issuance and consequently the CSR is not signed.
- looks that the hook is serialised looking for an output before to sign the CSR, and I´ve seen that with the new threading version on uwsgi service restart is complaining that threading is not enabled and it can be enabled, but not sure if is something should be done on the service itself, as haven't seen acme_srv.cfg parameter for that.


Under my point of view the non-signing of the certificate due a hook failure should be avoidable and of course if using threading, the signing of CSR shouldn't depend on hook to be executed, isn't?

**Comment by flphrrr** [comment]
Related to threading I have enabled it adding` enable-threads = true` on acme2certifier.ini 😄

**Comment by mlegner** [comment]
@flphrrr

> If the hooks experience an exception It causes an error on the overall Certificate Issuance and consequently the CSR is not signed with a failure return 400..

> Under my point of view the non-signing of the certificate due a hook failure should be avoidable and of course if using threading, the signing of CSR shouldn't depend on hook to be executed, isn't?

That's a good question. My implementation was under the assumption that the hook is essential in some way. In that case, if the hook fails for some reason and the certificate is returned, the client would assume that everything worked and wouldn't retry. So by failing, we force the client to retry the whole process until the hook works as well.

But I also see use cases where the hook would be allowed to fail. This would require adaptations of the code.

WDYT, @grindsa?

**Comment by grindsa** [comment]
I was also under the assumption that successful hook execution would be essential for certificate issuance and delivery to client. How about making this configurable?

**Comment by flphrrr** [comment]
@grindsa , it depends of the priority one can provide to the hook, on my case I see a priority 1 the certificate issuance vs the hook, as sometime the hook could trigger an informational action or an action that can be fixed afterwards, but never to imply a certissuance failure

**Comment by grindsa** [comment]
i am thinking about a kind of `ingore_hook_failure` option in acme_srv.cfg. In case its `True` a2c wont issue a certificate / ship an issued certificate to client; if `False` the certificate issuance/delivery takes presedence.

**Comment by flphrrr** [comment]
Yes, I agree with that approach, at least one can decide if the hook is at the same level of priority of the certificate issuance or not

**Comment by grindsa** [comment]
ok. I can look into this during next few days except @mlegner wants to take it (Honour to whom honour is due)...

**Comment by mlegner** [comment]
Hehe, thanks @grindsa. I will try to find some time for this today and create a PR against your `hooks` branch. If I don't manage, please just move ahead without me. :smile:

**Comment by flphrrr** [comment]
@grindsa , @mlegner.. after few improvements on the hook, here is an interesting result I´m getting when executing a complex hook, and maybe could improve adding hook_timeout and/or ignore_hook_failure:

```syslog
Certificate._info(timeout)
DBstore.certificate_lookup(name:timeout)
DBStore._certificate_search(column:name, pattern:timeout)
```

mainly although the hook succeeds, as the overall certificate issuance process is not able to get result on an expected time.. it fails with timeout.. and that for sure must be avoidable

**Comment by flphrrr** [comment]
@grindsa, @mlegner , after increasing the `Certificate` `enrollment_timeout` from 5 to 30 seconds it sorted the timeout issue.. so now working on reducing hook times

**Pull request merged**
