### PR TITLE
crude ACME backend polling

### PR DESCRIPTION
**Pull request by alesuiss**
Hello,

This is more of a documented feature-request than a plea to merge the actual code, which is rather crude (cf below).

For context: we started having problems with the ACME CA handler, because our ACME provider became too slow, causing timeouts on the client side with some clients: by the time acme2certifier got the certificate, the client has closed the connection. This cascaded into a broader problem of not being able to issue any certificates at all from any clients, I'll spare you the detail.

This is therefore a (very crude) implementation of the `poll` method for the handler (and also some code in `order.py` that was missing to trigger the polling, also crude and possibly wrong). It simply runs the enrolling code in a thread and returns immediately; subsequent polls try to wait on the thread with a timeout. I use a hash of the CSR as an identifier to find the thread and it's results in a global dict (I don't understand how the `poll_identifier` variable should be used, it doesn't seem to be provided by the client in polling requests). 

It's pretty bad, as it has a possibility of resource leak (if clients send orders and never poll them), and needs a specific uwsgi configuration (single non-master process) because of the global state. It works for us in a pinch, but a proper implementation would need a bit more thought. 

Sorry about contributing such lousy code; I can't afford the time to do it properly at the moment. Hopefully you can still do something useful with it :-)

### CODE REVIEW

**Comment by grindsa** [comment]
Sorry for not responding earlier but I am swamped with work right now. I will look into this during the weekend...

**Comment by alesuiss** [comment]
Hello,

- didn't measure it, but it must have been a bit over 30s which was the hard-coded timeout of a particular client (Traefik)
- a variety of them; Traefik showed the issue first with its low 30s timeout, but others soon followed
- depends on the client; some respect Retry-After, others retry after an arbitrary amount of time (we're not using any in-house clients)

Since then though, I've come to realize, this asynchronous behavior is really required for an ACME CA handler to be robust. ACME servers often have rate-limiting; without the async behavior, a single rate-limiting event can cascade into total failure, as more certificates are requested, generated and never returned to the clients, which keep retrying, generating yet more signing requests. I believe that's what happened to us, as pretty much all clients eventually stopped working as the signing delay started exceeding each client's timeout.

With the fix, properly written clients will retry after their timeout, and eventually get a `valid` result and be able to fetch their certificates, with no issues I've seen so far.

**Comment by grindsa** [comment]
Thank you for your answers. I agree that an asynchronous enrolment is needed, but it should not depend on the ca handler type. I like your approach to use the `threading` module and started to work on an more general solution based on your approach. Give me one day or two to get it done. First results are looking promising but require some careful testing.

**Comment by alesuiss** [comment]
Excellent, thank you! Indeed, I guess the behavior can be generalized to any CA handler

**Comment by grindsa** [comment]
I implemented asynchronous enrolment in a [separate branch](https://github.com/grindsa/acme2certifier/tree/enroll_timeout). Regression looks ok so feel free to give it a try.  But after looking into your changes I am not sure if this will finally solve your issue. (I cannot replicate your setup as I am missing an acme-server with slow response times.). Thus a quick question to you.  What kind of behaviour do you expect in below step 4 in your setup:

1. an acme-client not supporting "Retry-After" header requests a certificate
2. acme server response is delayed and client runs into timeout
3. acme server issues the certificate, certificate gets stored in local acme2certifier database
4. acme-client requests a certificate again, CSR is identical to the CSR in step-1

Should acme2certifier return the certificate stored in the database rather request a new one?

**Comment by alesuiss** [comment]
I'll have to find the time to test this in situ, but from a quick read it seems like it would work (while being conceptually simpler and getting rid of the potential resource leak issue in my initial implementation). Just one thing, if the `_enroll_and_store` fails (asynchronously), do you change the order status to "invalid" or something to return the error to the client? I don't see that in your code at first glance.

About your question, this is not a scenario I ran into, but I think it should never happen with either of our async implementations. As long as the thread join timeout is short enough, and acme2certifier returns 200 but leaves the order at "processing", the client should not re-send the same CSR, but just poll the order until no longer "processing" (AFAIK). But if it *did* happen, then IMO we should return the previously stored certificate (or we still risk runaway rate-limiting on the backend).

**Comment by grindsa** [comment]
Good catch. I forget to update the order status in case `_enroll_and_store` fails.  

I discovered the scenario I was describing above when using either lego or certbot. Both clients are not making use of the `Retry-After` header values but rather use an arbitrary timeout. If enrolment from CA takes longer than this timeout both clients will abort with a timeout error and use the same CSR when running again. But thanks for confirming my view. I will implement this behaviour during the upcoming days I just need to verify that this will not cause side-effects on renewal operations.

**Pull request merged**
